

// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY gouanlin. DO NOT CHANGE IT.
// </auto-generated>

using System;
using System.Buffers.Binary;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Gal.Core {
    public static class ReaderByteEx {


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static sbyte ReadInt8(this Reader<byte> self) => (sbyte)self.Read();


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static byte ReadUInt8(this Reader<byte> self) => self.Read();


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool ReadBoolean(this Reader<byte> self) => self.ReadUInt8() != 0;


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort ReadUInt16(this Reader<byte> self) {
            var t = SpanByteUtils.ReadUInt16(self.Span, false);
            self.Advance(sizeof(ushort));
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short ReadInt16(this Reader<byte> self) {
            var t = SpanByteUtils.ReadInt16(self.Span, false);
            self.Advance(sizeof(short));
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Int32 ReadInt32(this Reader<byte> self) {
            var t = SpanByteUtils.ReadInt32(self.Span, false);
            self.Advance(4);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UInt32 ReadUInt32(this Reader<byte> self) {
            var t = SpanByteUtils.ReadUInt32(self.Span, false);
            self.Advance(4);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Int64 ReadInt64(this Reader<byte> self) {
            var t = SpanByteUtils.ReadInt64(self.Span, false);
            self.Advance(8);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UInt64 ReadUInt64(this Reader<byte> self) {
            var t = SpanByteUtils.ReadUInt64(self.Span, false);
            self.Advance(8);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float ReadFloat(this Reader<byte> self) {
            var t = SpanByteUtils.ReadFloat(self.Span);
            self.Advance(sizeof(float));
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static double ReadDouble(this Reader<byte> self) {
            var t = SpanByteUtils.ReadDouble(self.Span);
            self.Advance(sizeof(double));
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint ReadVarUInt32(this Reader<byte> self) {
            var t = SpanByteUtils.ReadVarUInt32(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int ReadVarInt32(this Reader<byte> self) {
            var t = SpanByteUtils.ReadVarInt32(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong ReadVarUInt64(this Reader<byte> self) {
            var t = SpanByteUtils.ReadVarUInt64(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static long ReadVarInt64(this Reader<byte> self) {
            var t = SpanByteUtils.ReadVarInt64(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int ReadSleb128Int32(this Reader<byte> self) {
            var t = SpanByteUtils.ReadSleb128Int32(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static long ReadSleb128Int64(this Reader<byte> self) {
            var t = SpanByteUtils.ReadSleb128Int64(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string ReadUtf8(this Reader<byte> self, int len) {
            var t = SpanByteUtils.ReadUtf8(self.Span, len);
            self.Advance(len);
            return t;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string ReadUtf8(this Reader<byte> self) {
            var t = SpanByteUtils.ReadUtf8(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static sbyte ReadInt8(this Buffer<byte> self) => (sbyte)self.Read();


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static byte ReadUInt8(this Buffer<byte> self) => self.Read();


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool ReadBoolean(this Buffer<byte> self) => self.ReadUInt8() != 0;


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort ReadUInt16(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadUInt16(self.Span, false);
            self.Advance(sizeof(ushort));
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short ReadInt16(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadInt16(self.Span, false);
            self.Advance(sizeof(short));
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Int32 ReadInt32(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadInt32(self.Span, false);
            self.Advance(4);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UInt32 ReadUInt32(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadUInt32(self.Span, false);
            self.Advance(4);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Int64 ReadInt64(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadInt64(self.Span, false);
            self.Advance(8);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UInt64 ReadUInt64(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadUInt64(self.Span, false);
            self.Advance(8);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float ReadFloat(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadFloat(self.Span);
            self.Advance(sizeof(float));
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static double ReadDouble(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadDouble(self.Span);
            self.Advance(sizeof(double));
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint ReadVarUInt32(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadVarUInt32(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int ReadVarInt32(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadVarInt32(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong ReadVarUInt64(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadVarUInt64(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static long ReadVarInt64(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadVarInt64(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int ReadSleb128Int32(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadSleb128Int32(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static long ReadSleb128Int64(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadSleb128Int64(self.Span, out var count);
            self.Advance(count);
            return t;
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string ReadUtf8(this Buffer<byte> self, int len) {
            var t = SpanByteUtils.ReadUtf8(self.Span, len);
            self.Advance(len);
            return t;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string ReadUtf8(this Buffer<byte> self) {
            var t = SpanByteUtils.ReadUtf8(self.Span, out var count);
            self.Advance(count);
            return t;
        }

    }
}
