// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY gouanlin. DO NOT CHANGE IT.
// </auto-generated>

using System;
using System.Buffers.Binary;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Gal.Core {
    public static class WriterByteEx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteInt8(this IWriter<byte> self, sbyte value) {
            self.Write((byte)value);
            return self;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteUInt8(this IWriter<byte> self, byte value) {
            self.Write(value);
            return self;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteBoolean(this IWriter<byte> self, bool value) {
            self.Write(value ? (byte)1 : (byte)0);
            return self;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteUInt16(this IWriter<byte> self, UInt16 value) {
            var span = self.GetSpan(2);
            span[1] = (byte)(value >> 8);
            span[0] = (byte)value;
            self.Advance(2);
            return self;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteInt16(this IWriter<byte> self, Int16 value) {
            var span = self.GetSpan(2);
            span[1] = (byte)(value >> 8);
            span[0] = (byte)value;
            self.Advance(2);
            return self;
        }

        //      [MethodImpl(MethodImplOptions.AggressiveInlining)]
        //      public static IWriter<byte> WriteInt32(this IWriter<byte> self, Int32 value) {
        // Unsafe.WriteUnaligned(ref MemoryMarshal.GetReference(self.GetSpan(4)), !BitConverter.IsLittleEndian ? BinaryPrimitives.ReverseEndianness(value) : value);
        //          self.Advance(4);
        //          return self;
        //      }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TSelf WriteInt32<TSelf>(this TSelf self, int v) where TSelf : IWriter<byte> {
            Unsafe.WriteUnaligned(ref MemoryMarshal.GetReference(self.GetSpan(4)), !BitConverter.IsLittleEndian ? BinaryPrimitives.ReverseEndianness(v) : v);
            self.Advance(4);
            return self;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteUInt32(this IWriter<byte> self, UInt32 value) {
            Unsafe.WriteUnaligned(ref MemoryMarshal.GetReference(self.GetSpan(4)), !BitConverter.IsLittleEndian ? BinaryPrimitives.ReverseEndianness(value) : value);
            self.Advance(4);
            return self;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TSelf WriteUInt32<TSelf>(this TSelf self, UInt32 value) where TSelf : IWriter2<TSelf, byte> {
            Unsafe.WriteUnaligned(ref MemoryMarshal.GetReference(self.GetSpan(4)), !BitConverter.IsLittleEndian ? BinaryPrimitives.ReverseEndianness(value) : value);
            self.Advance(4);
            return self;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteInt64(this IWriter<byte> self, Int64 value) {
            Unsafe.WriteUnaligned(ref MemoryMarshal.GetReference(self.GetSpan(8)), !BitConverter.IsLittleEndian ? BinaryPrimitives.ReverseEndianness(value) : value);
            self.Advance(8);
            return self;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteUInt64(this IWriter<byte> self, UInt64 value) {
            Unsafe.WriteUnaligned(ref MemoryMarshal.GetReference(self.GetSpan(8)), BitConverter.IsLittleEndian ? BinaryPrimitives.ReverseEndianness(value) : value);
            self.Advance(8);
            return self;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static unsafe IWriter<byte> WriteFloat(this IWriter<byte> self, float value) => self.WriteInt32(*(int*)&value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static unsafe IWriter<byte> WriteDouble(this IWriter<byte> self, double value) => self.WriteInt64(*(long*)&value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteVarUInt32(this IWriter<byte> self, uint value) {
            var span = self.GetSpan(5);
            self.Advance(SpanByteUtils.WriteVarUInt32(ref span, value));
            return self;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteVarInt32(this IWriter<byte> self, int value) => self.WriteVarUInt32(ZigZagUtils.EncodeZigZag32(value));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteVarUInt64(this IWriter<byte> self, ulong value) {
            Span<byte> buffer = stackalloc byte[10];
            var e = SpanByteUtils.WriteVarUInt64(ref buffer, value);
            self.HintSize(e);
            buffer[..e].CopyTo(self.Span);
            self.Advance(e);
            return self;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IWriter<byte> WriteVarInt64(this IWriter<byte> self, long value) {
            self.WriteVarUInt64(ZigZagUtils.EncodeZigZag64(value));
            return self;
        }

        public static unsafe IWriter<byte> WriteUtf8(this IWriter<byte> self, string value) {
            if (string.IsNullOrEmpty(value)) {
                self.WriteInt16(0);
                return self;
            }

            ReadOnlySpan<char> chars = value;
            var maxLength = chars.Length * 3;

            if (self.WritableCount >= maxLength + 2) {
                var count = System.Text.Encoding.UTF8.GetBytes(chars, self.Span[2..]);
                if (count > short.MaxValue) throw new ArgumentOutOfRangeException(nameof(value));
                self.WriteUInt16((ushort)count);
                self.Advance(count);
            } else {
                var count = System.Text.Encoding.UTF8.GetByteCount(chars);
                self.WriteUInt16((ushort)count);
                var span = self.GetSpan(count);
                System.Text.Encoding.UTF8.GetBytes(chars, span);
                self.Advance(count);
            }

            return self;
        }
    }
}
