
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY gouanlin. DO NOT CHANGE IT.
// </auto-generated>

using System;
using System.Buffers.Binary;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Gal.Core {
    public static class WriterByteEx {


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteInt8(this Writer<byte> self, sbyte value) {
            self.Write((byte)value);

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteUInt8(this Writer<byte> self, byte value) {
            self.Write(value);

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteBoolean(this Writer<byte> self, bool value) {
            self.Write(value ? (byte)1 : (byte)0);

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteUInt16(this Writer<byte> self, ushort value) {
            self.Advance(SpanByteUtils.WriteUInt16(self.GetSpan(sizeof(ushort)), value, false));

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteInt16(this Writer<byte> self, short value) {
            self.Advance(SpanByteUtils.WriteInt16(self.GetSpan(sizeof(short)), value, false));

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteInt32(this Writer<byte> self, Int32 value) {
            self.Advance(SpanByteUtils.WriteInt32(self.GetSpan(4), value, false));

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteUInt32(this Writer<byte> self, UInt32 value) {
            self.Advance(SpanByteUtils.WriteUInt32(self.GetSpan(4), value, false));

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteInt64(this Writer<byte> self, Int64 value) {
            self.Advance(SpanByteUtils.WriteInt64(self.GetSpan(8), value, false));

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteUInt64(this Writer<byte> self, UInt64 value) {
            self.Advance(SpanByteUtils.WriteUInt64(self.GetSpan(8), value, false));

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteFloat(this Writer<byte> self, float value, bool bigEndian = false) {
            self.Advance(SpanByteUtils.WriteFloat(self.GetSpan(sizeof(float)), value, bigEndian));

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteDouble(this Writer<byte> self, double value, bool bigEndian = false) {
            self.Advance(SpanByteUtils.WriteDouble(self.GetSpan(sizeof(double)), value, bigEndian));

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteVarUInt32(this Writer<byte> self, uint value) {
            if (self.WritableCount >= 5) {
                self.Advance(SpanByteUtils.WriteVarUInt32(self.Span, value));
            } else {
                var size = SpanByteUtils.GetVarUInt32Size(value);
                self.Advance(SpanByteUtils.WriteVarUInt32(self.GetSpan(size), value));
            }

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteVarInt32(this Writer<byte> self, int value) {
            if (self.WritableCount >= 5) {
                self.Advance(SpanByteUtils.WriteVarInt32(self.Span, value));
            } else {
                var size = SpanByteUtils.GetVarInt32Size(value);
                self.Advance(SpanByteUtils.WriteVarInt32(self.GetSpan(size), value));
            }

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteVarUInt64(this Writer<byte> self, ulong value) {
            if (self.WritableCount >= 10) {
                self.Advance(SpanByteUtils.WriteVarUInt64(self.Span, value));
            } else {
                var size = SpanByteUtils.GetVarUInt64Size(value);
                self.Advance(SpanByteUtils.WriteVarUInt64(self.GetSpan(size), value));
            }

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteVarInt64(this Writer<byte> self, long value) {
            if (self.WritableCount >= 10) {
                self.Advance(SpanByteUtils.WriteVarInt64(self.Span, value));
            } else {
                var size = SpanByteUtils.GetVarInt64Size(value);
                self.Advance(SpanByteUtils.WriteVarInt64(self.GetSpan(size), value));
            }

            return self;

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Writer<byte> WriteUtf8(this Writer<byte> self, string value, bool bigEndian = false) {
            if (string.IsNullOrEmpty(value)) {
                self.Advance(SpanByteUtils.WriteUtf8(self.GetSpan(sizeof(ushort)), value, bigEndian));
                return self;
            }

            var maxLength = value.Length * 3;
            if (self.WritableCount >= maxLength + sizeof(ushort)) {
                self.Advance(SpanByteUtils.WriteUtf8(self.Span, value, bigEndian));
            } else {
                var count = System.Text.Encoding.UTF8.GetByteCount(value);
                if (count > short.MaxValue) throw new ArgumentOutOfRangeException(nameof(value));
                self.Advance(SpanByteUtils.WriteUtf8(self.GetSpan(count + sizeof(ushort)), value, bigEndian));
            }

            return self;

        }

    }
}
