
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY gouanlin. DO NOT CHANGE IT.
// </auto-generated>

using System;
using System.Buffers.Binary;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Gal.Core {
	public static class RefWriterBytesEx {


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteInt8(this ref RefWriter<byte> self, sbyte value) {
            self.Write((byte)value);

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteBoolean(this ref RefWriter<byte> self, bool value) {
            self.Write(value ? (byte)1 : (byte)0);

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt16(this ref RefWriter<byte> self, ushort value) {
            self.Advance(SpanByteUtils.WriteUInt16(self.GetSpan(sizeof(ushort)), value, false));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteInt16(this ref RefWriter<byte> self, short value) {
            self.Advance(SpanByteUtils.WriteInt16(self.GetSpan(sizeof(short)), value, false));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteInt32(this ref RefWriter<byte> self, Int32 value) {
            self.Advance(SpanByteUtils.WriteInt32(self.GetSpan(4), value, false));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt32(this ref RefWriter<byte> self, UInt32 value) {
            self.Advance(SpanByteUtils.WriteUInt32(self.GetSpan(4), value, false));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteInt64(this ref RefWriter<byte> self, Int64 value) {
            self.Advance(SpanByteUtils.WriteInt64(self.GetSpan(8), value, false));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt64(this ref RefWriter<byte> self, UInt64 value) {
            self.Advance(SpanByteUtils.WriteUInt64(self.GetSpan(8), value, false));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteFloat(this ref RefWriter<byte> self, float value) {
            self.Advance(SpanByteUtils.WriteFloat(self.GetSpan(sizeof(float)), value));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteDouble(this ref RefWriter<byte> self, double value) {
            self.Advance(SpanByteUtils.WriteDouble(self.GetSpan(sizeof(double)), value));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteVarUInt32(this ref RefWriter<byte> self, uint value) {
            self.Advance(SpanByteUtils.WriteVarUInt32(self.GetSpan(5), value));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteVarInt32(this ref RefWriter<byte> self, int value) {
            self.Advance(SpanByteUtils.WriteVarInt32(self.GetSpan(5), value));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteVarUInt64(this ref RefWriter<byte> self, ulong value) {
            self.Advance(SpanByteUtils.WriteVarUInt64(self.GetSpan(10), value));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteVarInt64(this ref RefWriter<byte> self, long value) {
            self.Advance(SpanByteUtils.WriteVarInt64(self.GetSpan(10), value));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteSleb128Int32(this ref RefWriter<byte> self, int value) {
            self.Advance(SpanByteUtils.WriteSleb128Int32(self.GetSpan(5), value));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteSleb128Int64(this ref RefWriter<byte> self, long value) {
            self.Advance(SpanByteUtils.WriteSleb128Int64(self.GetSpan(10), value));

        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUtf8(this ref RefWriter<byte> self, string value) {
            if (string.IsNullOrEmpty(value)) {
                self.Advance(SpanByteUtils.WriteUtf8(self.GetSpan(sizeof(ushort)), value));
                return ;
            }

            var maxLength = value.Length * 3;
            if (self.WritableCount >= maxLength + sizeof(ushort)) {
                self.Advance(SpanByteUtils.WriteUtf8(self.Span, value));
            } else {
                var count = System.Text.Encoding.UTF8.GetByteCount(value);
                if (count > short.MaxValue) throw new ArgumentOutOfRangeException(nameof(value));
                self.Advance(SpanByteUtils.WriteUtf8(self.GetSpan(count + sizeof(ushort)), value));
            }

        }
    }
}
